# Generated by Django 2.0.6 on 2018-06-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180604_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='ttl',
            field=models.IntegerField(default=15),
        ),
    ]
