# Generated by Django 2.0.6 on 2018-06-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20180604_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='expiration_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
