# Generated by Django 2.0.6 on 2018-06-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180604_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='ttl',
            field=models.IntegerField(default=5),
        ),
    ]
