version: '3'

services:
  migrations:
    image: web1
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
  web:
    image: web1
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
